Hide 'Teams' nav menu from normal texter accounts.
StateVoicesNational/Spoke pull request #1045
Opened 2019-01-31 20:20 UTC by bchrobot

This removes the Teams list and header from the dropdown navigation menu in the upper left for users with only the `TEXTER` role.

2019-02-01 02:04 UTC, joemcl commented
@bchrobot - 
- You mean the dropdown nav menu in the upper right, yes?
- Why do we use the word Teams, anyway? Should it not be Organizations?

2019-03-14 17:37 UTC, shakalee14 approved these changes

2019-03-21 20:46 UTC, schuyler1d requested changes
I think I object to the purpose of this PR.  Why should the 'teams' be hidden from the texter if they are part of multiple organizations?
Workflow might be "login to spoke.example.com" and if they are part of multiple teams, having the menu would be the only way they could get to the right view.

If someone really shouldn't see the mulitple orgs they are in then have an environment variable for that choice.

Also on the implementation side, even if the client caches this, it's still too many calls -- especially a 'thundering herd of volunteers'.  If this were implemented it should call `user.organizations(role='SUPERVOLUNTEER')` from the parent component and then just hide/show the whole menu depending on if there are any answers.

2019-03-22 15:44 UTC, closed without merging

2019-03-22 16:17 UTC, schuyler1d commented
I'd be :+1: to adding (or maybe even moving) those routes.