Fix bulk send
StateVoicesNational/Spoke pull request #1284
Opened 2019-11-21 07:32 UTC by lperson

# Fixes #1283 

## Description

This PR fixes bulk send, which is used outside the USA to send more than one initial message with a single button click.  It hadn't gotten any love in a while and when Australian Youth Climate Action tried to use the feature, no messages got sent. 

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

2019-11-21 22:13 UTC, schuyler1d requested changes
I like the move from the overly enormous schema.js of these important and complex mutations.
This does make me a little nervous about the difficultly of merging this with other changes in a batch, but that can be the challenge of our staging merge.

I asked for a couple of test tweaks.  Can you also include a description of what you actually changed to fix this?  That's the other issue with the single diff that moves everything -- it's impossible to see what changed, so let's at least describe in the PR.  (in the future, please make a separate commit for changes vs. code movement/refactoring)

2019-11-21 22:13 UTC, schuyler1d commented on __test__/server/api/campaign.test.js
> +    console.timeEnd("func1");
remove `console.time*` functions here please (I accidentally left this in -- but am removing them from my previous tests soon)

2019-11-21 22:13 UTC, schuyler1d commented on __test__/server/api/campaign.test.js
> +describe("Bulk Send", async () => {
can you add a test above here that confirms that when NOT_IN_USA and/or ALLOW_SEND_ALL are not enabled that bulkSend fails or errors?

2019-11-25 20:51 UTC, lperson commented
@schuyler1d Thanks for the review.  This is ready to re-review.

2019-11-25 21:13 UTC, schuyler1d commented
Cool.  These are good tests and I can approve the content of the PR.
@lperson Can you get the tests passing?

2019-11-25 21:16 UTC, schuyler1d commented
@ibrand Please put/keep this PR 'on deck' for stage-main merge when tests are passing -- as a pre-step, would be useful to get reports on what files specifically conflict.  I believe my PR will but just to add a comment into the sendMessage call:
https://github.com/MoveOnOrg/Spoke/pull/1273/files#diff-e3e0c0fe13e813c7748359d6a931a6faR1163

2019-11-26 15:03 UTC, schuyler1d commented on __test__/server/api/campaign.test.js
> +    expect(result.errors[0]).toBeDefined();
It's fine to make this ambiguous if it's not consistent.  Can you add a comment on what it outputs?

2019-11-26 15:03 UTC, schuyler1d submitted a review, later dismissed
:+1:

2019-11-26 19:55 UTC, schuyler1d approved these changes
:+1:

2019-12-18 16:12 UTC, merged