ci: Add Github Actions
StateVoicesNational/Spoke pull request #1490
Opened 2020-04-18 07:15 UTC by tmc

Adds Github Actions for:

* Linting
* Unit Tests
* E2E Tests

2020-04-20 19:07 UTC, ibrand commented
hey @tmc ! We have Travis set up running tests and I've never used github actions. Will this conflict and/or be redundant with a Travis setup?

2020-04-20 19:12 UTC, schuyler1d commented
@ibrand can you review the lint rules here?

We need to remove the e2e tests which should probably be deleted -- they did not run consistently and may be 'dead' at this point.  @matteosb was thinking about moving toward Cypress.  Thoughts?

2020-04-21 17:18 UTC, tmc commented
> hey @tmc ! We have Travis set up running tests and I've never used github actions. Will this conflict and/or be redundant with a Travis setup?

It will not conflict. It's partially redundant.

As far as I can tell travis isn't set up to report results on PRs which this will do. Reporting results is a better volunteer experience.

2020-04-21 17:19 UTC, tmc commented on .github/workflows/lint.yaml
> +      uses: reviewdog/action-eslint@v1
it uses eslint and will only report for new violation, I believe.

2020-04-21 17:21 UTC, tmc commented
> @ibrand can you review the lint rules here?
> 
> We need to remove the e2e tests which should probably be deleted -- they did not run consistently and may be 'dead' at this point. @matteosb was thinking about moving toward Cypress. Thoughts?

I can pull out the e2e tests.

Personally I find pupeteer lighter weight and easy to use.

2020-04-21 19:06 UTC, matteosb commented
@tmc Travis is configured to run on every PR but reporting back to GitHub appears to have broken recently. I think @schuyler1d is looking into it.

RE: Pupeteer. I don't have experience with it but it looks pretty good, though maybe a little lower-level than Cypress? From a quick read of the documentation it looks like there are a number of pros and cons. If you are interested in getting involved with e2e testing I'd appreciate your feedback on the RFC:  https://github.com/MoveOnOrg/Spoke/issues/1494

2020-04-25 17:51 UTC, tmc commented
Pushed a commit removing e2e test workflow.

2020-04-29 20:52 UTC, schuyler1d requested changes
I like this, and after confirming that Github Actions is free, since it's a public repository, I'd like to try this.

Can we change the lint action to only run the prettier command that we run with prettierrc and package.json's lint-staged settings?

We're getting into a mode where a lot of collaboration is happening all at once and we don't want PRs to stay clean without lint churn, so that reviews and merges are easier.

If there's a way to run the eslint options only for NEW files, I'm game for that.

2020-04-29 21:29 UTC, tmc commented
@schuyler1d -- The lint action here should use the .eslintrc configuration in the root of the repository -- is there indication that it doesn't?

2020-04-30 03:35 UTC, schuyler1d commented
Right, but let's say I make an edit in lines from 10-12 in the file and then the eslint fixes lines 15-100.

1. It's hard to focus in review and see that 10-12 are the important parts
2. If another PR edits lines 50-60 then we get conflicts that are hard to merge.

If we get a clear moment to run eslint across the project then we can turn this on, but the last time we tried that eslint was causing miscompile errors in one section , so that's why we're where we are -- that's why I'd prefer disabled to deletion because we might be able to enable it in the future but right now let's stick with prettier which has stayed uptodate across changes.

2020-05-02 02:48 UTC, tmc commented
> Right, but let's say I make an edit in lines from 10-12 in the file and then the eslint fixes lines 15-100.
> 
> 1. It's hard to focus in review and see that 10-12 are the important parts
> 2. If another PR edits lines 50-60 then we get conflicts that are hard to merge.
> 
> If we get a clear moment to run eslint across the project then we can turn this on, but the last time we tried that eslint was causing miscompile errors in one section , so that's why we're where we are -- that's why I'd prefer disabled to deletion because we might be able to enable it in the future but right now let's stick with prettier which has stayed uptodate across changes.

This change wouldn't fix lines X-U but would include warnings about them. I think this can serve as a nudge for authors to clean up files as they edit them.

2020-05-03 16:12 UTC, tmc commented
@schuyler1d Pulled out linting. Opened https://github.com/MoveOnOrg/Spoke/issues/1527 for later treatment. PTAL

2020-05-05 16:01 UTC, schuyler1d approved these changes
:+1:

2020-05-06 00:05 UTC, merged