Ag/hide branched scripts
StateVoicesNational/Spoke pull request #1815
Opened 2020-09-08 17:57 UTC by agreenspan24

## Description

Users can add the HIDE_BRANCHED_SCRIPTS config to hide all of the interactions workflow. The user will instead select an "Initial Outbound" message and then populate Canned Responses. This is to help simplify the texter's UI, make the conversation flow more freely, and simplify the campaign creation process. 

In total, this:
- Renames some help text
- Hides the interaction/question UI on campaigns
- Hides the question/responses in the texter view
- Adds a search bar for canned responses in the canned response options (we expect substantially more canned responses will be allowed.
- Makes the message text bar effectively a search bar: shortcuts are always shown and get filtered to what's been typed (case insensitive).

![image](https://user-images.githubusercontent.com/14208147/90698295-f9cffe00-e245-11ea-969c-96dc45ea6706.png)
![image](https://user-images.githubusercontent.com/14208147/90698305-fd638500-e245-11ea-8409-293d2ff47b03.png)
![image](https://user-images.githubusercontent.com/14208147/90698314-018fa280-e246-11ea-947e-c60a66a3955f.png)

# Checklist:

- [x] I have manually tested my changes on desktop and mobile
- [x] The test suite passes locally with my changes
- [x] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [x] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [x] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] My PR is labeled [WIP] if it is in progress

2020-09-08 18:48 UTC, ibrand commented
I want to note that #1790 has a canned response search and we'll probably merge that in soon, so if you're able to resolve conflicts with that one that would be great.

In this experience, do canned responses record data? Or do you leverage tags that link to canned responses for that?

2020-09-09 13:16 UTC, schuyler1d commented
Yeah, I'd prefer search filter connected to the number of canned responses (which I believe #1790 does) rather than this option so it's relevant to both, but I like that this config option can simplify the interface for folks wanting to set it up like this.

2020-09-09 16:17 UTC, agreenspan24 commented
@ibrand, there's some separate work that I'm adding to allow the actions we use on questions to also work on canned responses. That handles our data sync for canned responses. But the work there is extensive, plus requires new DB changes, so I figured I'd try to get that incorporated after the election. 

I'm happy to use the search bar work in #1790 rather than my own. Any sense of when that will be merged? Should I merge it in now or later? Also, do you want to try and rush this for the next release?

CC: @schuyler1d

2022-03-23 21:33 UTC, crayolakat requested changes
Hey @Arique1104 , here is my feedback regarding the merge conflict resolutions done in  commit 6e99e566e8fb870fc1104f61750b67bd231f5022:

`src/components/AssignmentTexter/Controls.jsx`:
The syntax is invalid and causing compilation issues. `getShortButtonText` and `toggleContactList` should be 2 separate functions.

`src/containers/AdminCampaignStats.jsx`:
The line `<Typography variant="h5">Survey Questions</Typography>` should replace `<div className={css(styles.header)}>Survey Questions</div>` instead of being added below it.

Could you review my suggested changes and update as needed?

2022-03-23 21:33 UTC, crayolakat commented on src/components/AssignmentTexter/Controls.jsx
>    };
```suggestion
  getShortButtonText = (text, limit) => {
    var sanitizedText = text.replace(/^(\+|\-)/, "");
    return (
      sanitizedText.slice(0, limit) +
      (sanitizedText.length > limit ? "..." : "")
    );
  };

  toggleContactList = () => {
    this.setState({ contactListOpen: !this.state.contactListOpen }, () => {
      setCookie("assignmentContactListOpen", this.state.contactListOpen, 1);
    });
  };
```

2022-03-23 21:33 UTC, crayolakat commented on src/containers/AdminCampaignStats.jsx
> +
```suggestion
          <Typography variant="h5">Survey Questions</Typography>
        )}
```

2022-03-24 02:43 UTC, agreenspan24 commented on src/components/AssignmentTexter/Controls.jsx
>    };
Looked good to me!

2022-03-24 02:44 UTC, agreenspan24 commented on src/containers/AdminCampaignStats.jsx
> +
Looked good to me!

2022-03-24 16:15 UTC, crayolakat approved these changes

2022-06-02 22:42 UTC, merged