Return informative errors from GraphQL endpoint:w
StateVoicesNational/Spoke pull request #1932
Opened 2021-02-22 00:06 UTC by lperson

## Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change, and any blockers that make your change a WIP_

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

2021-02-23 16:03 UTC, schuyler1d requested changes
The point of the logic there is to restrict what kind of error is revealed.  If you want to make changes, then do so up here:
https://github.com/MoveOnOrg/Spoke/pull/1932/files#diff-846e308afe343fa0238d38943beed033bec2ab41582b904029a4ef0106d634a1R194-R196
and enable SHOW_SERVER_ERROR=1 or DEBUG=1 on your instance

2021-02-23 16:09 UTC, lperson commented
https://github.com/MoveOnOrg/Spoke/pull/1932/files#diff-846e308afe343fa0238d38943beed033bec2ab41582b904029a4ef0106d634a1L196

Do you agree that line should be a GraphQLError, not Error.

2021-02-23 16:25 UTC, schuyler1d commented
Yes!

2021-03-08 19:56 UTC, schuyler1d approved these changes
:+1:

2021-04-28 14:49 UTC, merged