Twilio env variables
StateVoicesNational/Spoke pull request #2062
Opened 2021-10-21 15:56 UTC by Arique1104

# Removes TWILIO_STATUS_CALLBACK_URL variable from .env.example and app.json
# (issue)

## Description

_Removes the variable TWILIO_STATUS_CALLBACK_URL from .env.example and app.json in order to _

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [x] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

2021-10-21 19:31 UTC, crayolakat requested changes
Thanks! Can you also remove `TWILIO_MESSAGE_CALLBACK_URL` from `.env.example` and `app.json`? `TWILIO_MESSAGE_CALLBACK_URL` is in the same boat as `TWILIO_STATUS_CALLBACK_URL` in the fact that it should be set per organization instead of as environment variables.

References to these 2 environment variables should also be removed from `docs/HOWTO_INTEGRATE_TWILIO.md` and `docs/REFERENCE-environment_variables.md`

2021-10-21 21:37 UTC, Arique1104 commented
> Thanks! Can you also remove `TWILIO_MESSAGE_CALLBACK_URL` from `.env.example` and `app.json`? `TWILIO_MESSAGE_CALLBACK_URL` is in the same boat as `TWILIO_STATUS_CALLBACK_URL` in the fact that it should be set per organization instead of as environment variables.
> 
> References to these 2 environment variables should also be removed from `docs/HOWTO_INTEGRATE_TWILIO.md` and `docs/REFERENCE-environment_variables.md`

For additional Twilio environment variables for advanced use cases consult the Twilio Service Vendor Extension Code. 

Go look at this file: https://github.com/MoveOnOrg/Spoke/blob/main/src/extensions/service-vendors/twilio/index.js

2021-11-09 22:50 UTC, Arique1104 commented
- [ ] remove TWILIO_MESSAGE_CALLBACK_URL from .env.example and app.json? 
- [ ] TWILIO_MESSAGE_CALLBACK_URL is in the same boat as TWILIO_STATUS_CALLBACK_URL in the fact that it should be set per organization instead of as environment variables.
- [ ] Remove references to these 2 environment variables should also be removed from:
- [ ] docs/HOWTO_INTEGRATE_TWILIO.md and 
- [ ] docs/REFERENCE-environment_variables.md

2021-11-10 00:21 UTC, crayolakat approved these changes
Looks great!

2022-03-18 19:29 UTC, merged

2022-03-20 04:33 UTC, daradib commented on app.json
> -    "TWILIO_MESSAGE_SERVICE_SID": {
This differs from the changes to `.env.example`. Was this intended to remove `TWILIO_MESSAGE_CALLBACK_URL` instead, which was never defined in `app.json`?