npm script to automate tunnelling on dev environment using Ngrok
StateVoicesNational/Spoke pull request #367
Opened 2017-11-02 23:51 UTC by benmort

2017-11-06 22:24 UTC, schuyler1d requested changes
changes just to make sure it's truly optional

2017-11-06 22:24 UTC, schuyler1d commented on package.json
> +    "tunnel": "node ./tunnel.js"
I think we want something like `if [ "$NGROK_AUTH_TOKEN" != \"\" ] ; then node ./tunnel.js; fi` for the tunnel job -- basically it should be able to work without ngrok.

2017-11-06 22:24 UTC, schuyler1d commented on .env.example
> +PORT=_integer_
Does the `_integer_` etc provide info to some IDE?  If so, this is cool.  However, if it's just a textual hint, I'd rather they be blank in this file, so when people copy it over, if they don't modify the line at all, then it stays an empty value (and e.g. tests if the value exist will do the right thing)

2018-02-09 15:33 UTC, schuyler1d commented
reopening after moving to main

2021-03-19 14:39 UTC, Frydafly commented
Closing since this is pretty old, and created an issue https://github.com/MoveOnOrg/Spoke/issues/1951 in order to not abandon this project!

2021-03-19 14:39 UTC, closed without merging