Support for multimedia (#266)
StateVoicesNational/Spoke pull request #425
Opened 2017-12-03 20:22 UTC by ben-pr-p

Hey!

This adds support for images in texts. The syntax is, in any message, `[https://image-url.com/image-is-here]`.

<img width="932" alt="screen shot 2017-12-03 at 2 19 54 pm" src="https://user-images.githubusercontent.com/10324926/33529329-32dc9b04-d835-11e7-85bb-b333c9173ddf.png">

And the result:

![img_0122](https://user-images.githubusercontent.com/10324926/33529356-69378b0a-d835-11e7-9c05-0799b7b93242.PNG)

2017-12-03 20:30 UTC, schuyler1d requested changes
:+1: 
after we tweak the regex.  This is great!

2017-12-03 20:30 UTC, schuyler1d commented on src/server/api/lib/twilio.js
> +    const extractor = new RegExp(/\[.*http(.*)\]/)
I think the first `.*` should be `\s*` and the second you probably want `([^\]]*)` to be a little safer

2017-12-04 02:56 UTC, schuyler1d approved these changes

2017-12-04 16:19 UTC, jmcarp commented on src/server/api/lib/twilio.js
> +    const extractor = new RegExp(/\[\s*(http[^\]\s]*)\s*\]/)
WDYT about moving this to a separate function and adding tests?

2017-12-15 11:05 UTC, shakalee14 commented
this is ready to be merged and was qa'd on stage

2017-12-15 14:52 UTC, merged

2018-08-23 19:46 UTC, joemcl commented
I'm trying to send a small test campaign with an image - not working so far. 
The number I'm sending is MMS-enabled in Twiio, just checked. 
The Twilio message log  shows an unhelpful error message - (Error:30008)Unknown error. 
The link I'm using is [https://drive.google.com/file/d/1i6X8OmTqCLEdbhTxXHbnaZFvmTZ7StNQ/view?usp=sharing], that's OK, just tried that in an 'incognito window' . 
Checking if there's some Heroku setting I need to change/tweak. 
I'm using our staging Spoke instance, it works fine for test campaigns sending plain text.

2018-08-23 19:54 UTC, joemcl commented
Thanks @bchrobot *shouldn't* matter - the link and image is public - but of course it might :) cause  Google. So I'll check out imgur.com. In the test above, is that i.ytimg.com link produced by imgur.com or, like, YouTube? Some other site?

2018-08-23 20:11 UTC, joemcl commented
OK @bchrobot thanks, so this link worked, hosted on imgur - https://i.imgur.com/lv66Kzg.jpg - a 'Direct Link'. 
An imgur 'Image Link' like https://imgur.com/lv66Kzg (does not contain file type suffix .jpg) did not. 
Thanks!