41 pm2 prod process
StateVoicesNational/Spoke pull request #56
Opened 2017-07-19 21:35 UTC by sreynen

For #41 .

2017-07-20 00:39 UTC, shakalee14 commented on .babelrc
> +    "transform-runtime"
great - glad babel-runtime was the way to go

2017-07-20 00:39 UTC, shakalee14 commented on README.md
> +3. Make a copy of `spoke-pm2.config.js.template`, e.g. `spoke-pm2.config.js`, add missing creds, and run it with [pm2](https://www.npmjs.com/package/pm2), e.g. `pm2 start spoke-pm2.config.js --env pr
instead of creds, can we say 'environment variables'

2017-07-20 00:39 UTC, shakalee14 commented on package.json
> +    "start": "node ./build/server/server",
do we still need ``OUTPUT_DIR`` as a env variable then if we're going to hardcode ``./build``?

2017-07-20 00:39 UTC, shakalee14 commented on spoke-pm2.config.js.template
> +  OUTPUT_DIR:'./build',
I believe we can remove ``OUTPUT_DIR``

2017-07-20 00:39 UTC, shakalee14 commented on spoke-pm2.config.js.template
> +        COMMON_VARIABLE: 'true'
great! did we ever figure out what ``COMMON_VARIABLE`` does?

2017-07-24 17:22 UTC, shakalee14 commented
hey @sreynen  did you have a chance to respond to my review?

2017-07-24 17:29 UTC, sreynen commented on spoke-pm2.config.js.template
> +        COMMON_VARIABLE: 'true'
I believe that's just example config, not actually used for anything. `env` is just environment variables that get loaded regardless of the `--env` flag, so this is passing an environment variable named `COMMON_VARIABLE` to node, which isn't being used.

2017-07-24 17:35 UTC, sreynen commented on package.json
> +    "start": "node ./build/server/server",
This change was already made to the prod instance before I started working on it, so I don't know what the motivation was.

2017-07-24 17:40 UTC, shakalee14 commented on spoke-pm2.config.js.template
> +        COMMON_VARIABLE: 'true'
ok - then we can remove it?

2017-07-31 19:47 UTC, shakalee14 commented on spoke-pm2.config.js.template
> +      name      : 'number-assigner',
@sreynen shouldn't we remove this number-assigner worker?

2017-07-31 19:56 UTC, shakalee14 requested changes
See comment about number-assigner.

2017-08-01 13:05 UTC, shakalee14 approved these changes

2017-08-01 13:06 UTC, shakalee14 approved these changes

2017-08-01 14:15 UTC, merged