wip: iterates by STEPs for groups and can delegate to a new invoked lambda for each call
StateVoicesNational/Spoke pull request #700
Opened 2018-07-11 20:18 UTC by schuyler1d

fixes #672 

TODO: 1. make sendJobToAWSLambda actually work. 2. make the jobEvent.command correct and work 3. vary STEP to be 10 for sqlite (which hits a maximum value issue then) and 10000 for production (and postgres)

2018-07-17 14:47 UTC, mathemagica requested changes

2018-07-17 14:47 UTC, mathemagica commented on src/workers/jobs.js
> +  if (totalParts > 1 && /LIMIT/.test(sqlQuery)) {
Let's add a comment here explaining why: "We're instrumenting this query with limit / offset to implement batching results back from this query, to get back currently scaling limitations. It'd be way more complicated to implement batching with a query that already does some batching itself, so we do the easier thing here and check whether queries contain LIMIT, and if so, give the user an error so they can rewrite this query to not preemptively batch."

2018-07-17 14:47 UTC, mathemagica commented on lambda.js
> -exports.handler = (event, context) => {
lets put a PSA comment here that lambda doesnt know its actually done (and may retry on perceived failure) unless handleCallback is called (eek)

2018-07-17 14:47 UTC, mathemagica commented on src/workers/jobs.js
> +  } else if (jobEvent.part < (jobEvent.totalParts - 1)) {
lots of complexity in here, and when we have a reliable unit test framework that can setup and tear down dbs without race conditions, i'd ask that you create unit tests for cases: single batch < 10K in size, a batch > 10K, a batch of exactly 30K (to check for off by one errors). For now, could you create unit test stubs with descriptive names so we dont forget to unit test this later?

2018-07-19 14:26 UTC, mathemagica approved these changes
👍

2018-07-23 17:32 UTC, azuzunaga commented
## QA feedback:
### Instructions
1) Hit the + button to create a new campaign
2) Go to the contacts tab, copy paste query (may have to add AS statements for validation.. for example columns should be `first_name`, `last_name`, `cell`) run query
3) Wait for it to load - make sure it completes & try to keep up with time it takes to complete
4) Archive campaign

### Results:
- It takes +1 min to load contacts from any query.
- Can’t tell when contacts are loading, how long until all contacts finish loading, or whether there is a query error.
  - Silent fail on query error (introduced a typo)
- After contacts have been added they don’t show up under *Already texted* or *Available to assign*
- In the SQL input text field, `SELECT` form validation is case-sensitive.
- Query `select distinct(cell), first_name, last_name from spoke.campaign_contact where is_opted_out=false limit 150000` didn’t load after 15 mins

2018-08-09 16:58 UTC, merged