Caching assignments and messages
StateVoicesNational/Spoke pull request #939
Opened 2018-09-24 15:22 UTC by schuyler1d

* Continuation of #920 
  - [x] (re)load assignment and assignmentcontact info on assignTexters() job and campaignStart
  - [x] expire assignments ?24 hours?
  - [x] updateMessageStatus (in assignment-contacts) methods and wiring based on messaging

Includes:
 - [x] cached messages
 - [x] cached assignments
 - [x] mostly-activated campaign-contact data
 - [x] more [cacheable_queries documentation](https://github.com/MoveOnOrg/Spoke/blob/scaling-
Premerged with:
 - [x] assignment tests from https://github.com/MoveOnOrg/Spoke/pull/933
 - [x] https://github.com/MoveOnOrg/Spoke/pull/916 user cache refactor

messages/src/server/models/cacheable_queries/README.md)
Does NOT include
* dynamic assignment improvement
* cached user.todos (user assignments)

### Possible bugs to investigate:
 - [ ] first load on todos screen gets timeout, but not after a reload

2018-09-25 19:57 UTC, azuzunaga approved these changes
Thanks for the walkthrough - looks good!

2018-09-26 16:25 UTC, azuzunaga requested changes

2018-09-27 17:06 UTC, azuzunaga submitted a review, later dismissed

2018-10-09 14:44 UTC, shakalee14 commented
Upon production deploy, encountered a bug where reply messages disappeared. When clicking on `send replies`, a texter would see a screen like this :

*note this isnt a reply message

<img width="1206" alt="screen shot 2018-10-09 at 10 34 26 am" src="https://user-images.githubusercontent.com/16676323/46677232-35accd80-cbb0-11e8-939c-5ff3729ffd24.png">

2019-02-21 03:31 UTC, schuyler1d commented
obsoleted by https://github.com/MoveOnOrg/Spoke/pull/965

2019-02-21 03:31 UTC, closed without merging